apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debugger
spec:
  workspaces:
    - name: shared-workspace
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        ls -la /workspace/shared-workspace
