apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smartfactory-ci-user-management-service-
spec:
  pipelineRef:
    name: smartfactory-ci-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    - name: maven-local-m2
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    - name: maven-settings
      emptyDir: { }
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  params:
    - name: REPO_URL
      value: https://github.com/DragomirAlin/smartfactory
    - name: PROJECT_DIR
      value: "user-management-service"
    - name: IMAGE
      value: "user-management-service"
    - name: TAG
      value: "latest"
    - name: ACCOUNT
      value: "dragomiralin"

