version: '3.8'

services:
  user-management-service:
    image: localhost:5001/user-management-service:local
    hostname: user-management-service
    container_name: user-management-service
    pull_policy: always
    networks:
      - smartfactory-net
    ports:
      - 8081:8080

volumes:
  db:
    driver: local

networks:
  smartfactory-net:
    name: smartfactory-net

